{
  "overview": "The Kingdom of Valoria is a micronation founded on February 7, 2025, by King Callistus (age 14) and his middle school friends in Lunglei, Mizoram. It started as a fun project and has grown to include territories, a military, a church, and an AI agency called Celestial Nexus. Keystone is the first AI created by Celestial Nexus, designed to communicate with top officials like lords and generals, providing advice, strategies, and knowledge about Valoria.",
  "founders": "Valoria was founded by three Great Lords: King Callistus (King and overall ruler, Instagram founder), Field Marshal Kaldor (Land Warfare Lord, founder of Modesty, known as Voidfather), and Father Zephyrus (first priest, Air Chief Marshal, Lord of Air Warfare, Father of the Nation). Other key lords: Prime Minister Aldric (government), Lord High Admiral (Naval Warfare), Astrarch Elion (first official lord, ruler of Modesty state).",
  "tribes": "Valoria has six tribes, each led by a lord. The kingdom's structure emphasizes leadership in warfare, governance, and spiritual matters.",
  "history": "Before Valoria, Astrarch Elion created a large Instagram group that became Caelumbra City. Field Marshal Kaldor added King Callistus to the group. Operation Potboil launched with 'We're cooking the cooked.' Elion, new in Class 9, renamed the group 'Slave Town of Valoria,' then King Callistus changed it to Caelumbra City, marking its birth. Before joining Valoria, Field Marshal Kaldor founded the Children Defence Force, later the Valorian Army.",
  "territories": "Valoria claims a 50-foot circle around wherever Valorians walk. Aetheron City is the capital (originally King Callistus's bedroom). Caelumbra City is capital of Modesty state, born from the Instagram group.",
  "military": "Valorian Army Private Limited (evolved from Children Defence Force), Valorian Blade (special forces), Royal Guards (protect king and leaders), King Callistus Carrier (wooden wheelbarrow), weapons include slingshots, sticks/stones, paper planes, paper boats.",
  "church": "Valoria has its own church, led by Father Zephyrus. Plans for a church book (like a Bible) containing Valoria's stories, history, and teachings."
    }
